# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [3]:
import pandas as pd
    
import numpy as np

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [5]:
a =pd.Series([100,200,300,400])

Print a, and data type

In [6]:
print(a)
type(a)

0    100
1    200
2    300
3    400
dtype: int64

pandas.core.series.Series

Using indexing access the element 300 from the series a.

In [7]:
a[2]

300

What are the values of index for series a?

In [17]:
a= pd.Series([100,200,300,400],index=["c","a","b","d"])

Change the index to  ['c', 'a', 'b', 'd']

In [18]:

a.head()

c    100
a    200
b    300
d    400
dtype: int64

Access the value in the series with index 'd'

In [19]:
print(a["d"])

400

Sort the values wrt to the index and print it

In [ ]:
a.sort_values("index",ascending=True)

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [24]:
 b = pd.Series([800,450,100],index=['e','f','g'])
b.head()

e    800
f    450
g    100
dtype: int64

Append b series at the end of a series

In [ ]:
a=a.append(b)

In [28]:
#print a again after appending b into it

a

c    100
a    200
b    300
d    400
e    800
f    450
g    100
dtype: int64

Sort the values in descending order of a and print the index of the sorted series

In [ ]:
a.sort_index(ascending=False)

g    100
f    450
e    800
d    400
c    100
b    300
a    200
dtype: int64

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [ ]:
df =pd.DataFrame({"a":[100,200,300,400]})

In [59]:
df

     a
0  100
1  200
2  300
3  400

What is the shape of the datafarme <br>
(also, what does it imply?)

In [60]:
df.shape

(4, 1)

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [53]:
# yep its same as the series.

print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [61]:

df.head() #head() returns the first 5 records and also we can customise the records to fetch according to user need

     a
0  100
1  200
2  300
3  400

In [62]:

df.tail() #tail() returns the last 5 records and also we can customise the records to fetch according to user need

     a
0  100
1  200
2  300
3  400

Rename the column of the dataframe as 'points'

In [63]:

df.columns=["points"]

df

   points
0     100
1     200
2     300
3     400

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [65]:
#Create fruits array

fruits =["orange","mango","apple","pineapple","graphes","pappaya","jackfruit"]

In [66]:
#Create series fruits out of fruits array

fruits =pd.Series(fruits)

Change the index of fruits to the index of dataframe df

In [68]:
fruits.index=[0,1,2,3,4,5,6]
fruits

0       orange
1        mango
2        apple
3    pineapple
4      graphes
5      pappaya
6    jackfruit
dtype: object

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

In [71]:

df["fruits"]=fruits

df.head()

   points     fruits
0     100     orange
1     200      mango
2     300      apple
3     400  pineapple

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [38]:
d1 =pd.DataFrame({"city":['Chandigarh', 'Delhi', 'Kanpur', 'Chennai', 'Manali' ],"Temperature":[15,22,20,26,-2]})

Print(d1)

In [39]:


d1.head()

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [41]:

d1.shape

(5, 2)

Set city = d1['city']

In [45]:
city=d1['city']

city

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: object

print city <br>
What is the type of city.

In [44]:

type(city)

pandas.core.series.Series

Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [46]:
d2 =pd.DataFrame({"city":['Bengalaru','coimbatore','srirangam','pondicherry'],"Temperature":[24,35,36,39]})

print the shape of this dataframe

In [47]:
d2.shape

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [158]:
d3 =pd.concat([d1,d2]) 
d3

          city  Temperature
0   Chandigarh           15
1        Delhi           22
2       Kanpur           20
3      Chennai           26
4       Manali           -2
0    Bengalaru           24
1   coimbatore           35
2    srirangam           36
3  pondicherry           39

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

In [51]:
d3[d3["Temperature"]<=20][["city"]]

         city
0  Chandigarh
2      Kanpur
4      Manali

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [52]:
d3[d3["Temperature"]>=35][["city"]]

          city
1   coimbatore
2    srirangam
3  pondicherry

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not. 
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [159]:
# write function here

def is_ut(x):
    if x['city']in["Chandigarh","pondicherry","Delhi"]:
        return True
    else:
        return False
            
    
d3['is_ut'] = d3.apply(is_ut,axis=1)

In [160]:
# print d3

d3

          city  Temperature  is_ut
0   Chandigarh           15   True
1        Delhi           22   True
2       Kanpur           20  False
3      Chennai           26  False
4       Manali           -2  False
0    Bengalaru           24  False
1   coimbatore           35  False
2    srirangam           36  False
3  pondicherry           39   True

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT - 
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [124]:
# write function here
def c_to_f(x):
    return (x*9/5)+32

In [126]:
# check function c_to_f(10)

c_to_f(10)

50.0

In [161]:
# apply function c_to_f to d3 to create a column 'temp_farenhiet'

d3['temp_farenhint']=d3["Temperature"].apply(c_to_f)
d3

          city  Temperature  is_ut  temp_farenhint
0   Chandigarh           15   True            59.0
1        Delhi           22   True            71.6
2       Kanpur           20  False            68.0
3      Chennai           26  False            78.8
4       Manali           -2  False            28.4
0    Bengalaru           24  False            75.2
1   coimbatore           35  False            95.0
2    srirangam           36  False            96.8
3  pondicherry           39   True           102.2

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [149]:

d3[d3['is_ut'] == True]

          city  Temperature  is_ut  temp_farenhint
0   Chandigarh           15   True            59.0
1        Delhi           22   True            71.6
3  pondicherry           39   True           102.2

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [153]:
d3[d3['temp_farenhint'] > 90]

          city  Temperature  is_ut  temp_farenhint
1   coimbatore           35  False            95.0
2    srirangam           36  False            96.8
3  pondicherry           39   True           102.2

Select only the first three rows of the dataframe d1.

In [114]:
d1.iloc[0:3,0:2]

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20

Select all the rows and last two columns in the dataframe.

In [148]:
d3.iloc[0:15,2:5]

   is_ut  temp_farenhint
0   True            59.0
1   True            71.6
2  False            68.0
3  False            78.8
4  False            28.4
0  False            75.2
1  False            95.0
2  False            96.8
3   True           102.2

## Groupby

In [74]:
# Create a dataframe using dictionary of your choice

data =pd.DataFrame({"name":["yaswanth","ravi","naveen","prasad","anil"],"class":["8th","9th","8th","8th","9th"],"subjects":["ns","ps","math","ps","math"],"marks":[540,340,450,320,390]})
data

       name class subjects  marks
0  yaswanth   8th       ns    540
1      ravi   9th       ps    340
2    naveen   8th     math    450
3    prasad   8th       ps    320
4      anil   9th     math    390

In [83]:
# Use Groupby of single column with aggregate sum()

data.groupby("class")[["marks"]].sum()

       marks
class
8th     1310
9th      730

In [84]:
# Use Groupby of single column with aggregate count()
data.groupby("subjects")[["name"]].count()

          name
subjects
math         2
ns           1
ps           2

In [90]:
# Use Groupby of single column with aggregate min() and max()
data.groupby('name')[["marks"]].max()
data.groupby('name')[["marks"]].min()

          marks
name
anil        390
naveen      450
prasad      320
ravi        340
yaswanth    540

In [91]:
# Use Groupby of any 2 columns with aggregate mean()
data.groupby(["class","subjects"])[["marks"]].mean()

                marks
class subjects
8th   math      450.0
      ns        540.0
      ps        320.0
9th   math      390.0
      ps        340.0

In [103]:
# Use Groupby of any 2 columns with aggregate min() and max()
data.groupby(["class","subjects"])[["marks"]].min()
data.groupby(["class","subjects"])[["marks"]].max()

                marks
class subjects
8th   math        450
      ns          540
      ps          320
9th   math        390
      ps          340

## Data Range

Create a pandas daterange where starting date is 1st of January,2020 and end date is 1st of April 2021, store it in a new variable named 'a'

In [104]:
a =pd.date_range(start="01-01-2020",end='01-04-2021')

print a

In [105]:
a

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2020-12-26', '2020-12-27', '2020-12-28', '2020-12-29',
               '2020-12-30', '2020-12-31', '2021-01-01', '2021-01-02',
               '2021-01-03', '2021-01-04'],
              dtype='datetime64[ns]', length=370, freq='D')

What is the len of a?

In [106]:
len(a)

370

What is the type of a?

In [107]:

type(a)

pandas.core.indexes.datetimes.DatetimeIndex